### ISSUE TITLE
Update API version

### ISSUE THREAD

**Issue by dorongutman** [verifalia/verifalia-ruby-sdk#19]
Currently the code uses version 1.4, but there's already version 2 of the api.

**Comment by ecobisi** [comment]
Thanks for your feedback, we are currently working to upgrade this SDK to the latest version of the API.

In the meantime, please note that version 1.4 - like every other API version we offered - will always be available, as we never drop support for older versions by design.

**Comment by dorongutman** [comment]
@ecobisi I understand, however:
1. Your API documentation is for version 2.0
1. Since the SDK doesn't use a Result object so I need to parse the JSON returned, changing to use version 2.0 after implementing 1.4 will require code changes.

Do you have any kind of vague time estimations as to when will you have the 2.0 sdk version?

**Comment by ecobisi** [comment]
@dorongutman I understand your points and fully agree with you.

While at the time of this writing we don't have a Ruby SDK targeting at version 2.0 of our API, I have managed to have the documentation for our older API available on our website:

https://verifalia.com/developers/previous-versions/api-v1

Also we estimate to have the Ruby SDK aligned with the latest version of our API in Q1/Q2 of this year.

**Comment by marcoadkins** [comment]
@ecobisi Any update on the v2 sdk?

**Comment by marcoadkins** [comment]
Anyone else stumbles upon this. I made a fork that works for account balance and email validation with v2 endpoints: https://github.com/marcoadkins/verifalia-ruby-sdk

**Comment by verifalia** [comment]
It took us a while but we have finally upgraded this SDK to the latest Verifalia API version.
