### ISSUE TITLE
Need to fix EmailValidations#completed? method 

### ISSUE THREAD

**Issue by pramodshinde** [verifalia/verifalia-ruby-sdk#4]
While using this sdk, found bug in EmailValidations#completed? method as following 
After creating validation job using 

``` ruby
unique_id = @client.email_validations.verify(emails)
response = @client.email_validations.query
```

Got response as 

``` javascript
{
   "uniqueID":"74169d7e-e8be-4ebb-aa5b-xxxxxxxx",
   "engineVersion":"1.2;2015-10-08",
   "submittedOn":"2015-10-20T12:27:40.023",
   "progress":{
       "noOfTotalEntries":3,
       "noOfCompletedEntries":2
   }
}
```

If we notice this job is in progress , I checked status using 

``` ruby
@client.email_validations.completed?
```

And got `true` which is incorrect. 

completed? method should be like 

``` ruby
def completed?
   query["progress"]["noOfTotalEntries"] == query["progress"]["noOfCompletedEntries"]
end
```

@verifalia  Waiting for your confirmation on this, So I can fix this and send PR.

**Comment by verifalia** [comment]
Hello,

your recent request has been received and has been assigned a ticket number of [14A-1DBA0D57-0105].  Please keep this ticket number for your records and include it in the subject (including brackets) of all future emails regarding this issue.  

Our support team will respond to your ticket as soon as possible. In the meanwhile, you may want to visit our knowledge base at:  http://verifalia.com/support/kb  - http://verifalia.com/support/kb 

Thank you.

--
Verifalia support
 http://verifalia.com  - http://verifalia.com   

   

----------------------------------------
From: verifalia/verifalia-ruby-sdk <reply@reply.github.com>
Sent: Wednesday, October 21, 2015 10:46 AM
To: verifalia/verifalia-ruby-sdk <verifalia-ruby-sdk@noreply.github.com>
Subject: [verifalia-ruby-sdk] Need to fix EmailValidations#completed? method  (#4)

While using this sdk, found bug in EmailValidations#completed? method as following 
After creating validation job using   

unique_id = @client.email_validations.verify(emails) response = @client.email_validations.query

Got response as   

{    "uniqueID":"74169d7e-e8be-4ebb-aa5b-xxxxxxxx",    "engineVersion":"1.2;2015-10-08",    "submittedOn":"2015-10-20T12:27:40.023",    "progress":{        "noOfTotalEntries":3,        "noOfCompletedEntries":2    } }

If we notice this job is in progress , I checked status using   

@client.email_validations.completed?

And got true which is incorrect.   

completed? method should be like   

def completed?    query["progress"]["noOfTotalEntries"] == query["progress"]["noOfCompletedEntries"] end

 @verifalia  - https://github.com/verifalia   Waiting for your confirmation on this, So I can fix this and send PR.
