### ISSUE TITLE
Configure CI builds, quality and documentation tools

### ISSUE THREAD

**Issue by RobertoSchneiders** [verifalia/verifalia-ruby-sdk#7]
It would be nice to have a automated build (CircleCI) for this repository. Also, would be very nice to have [Gemnasium](gemnasium.com), [Coveralls](coveralls.io), [Code Climate](codeclimate.com), [inch-ci](http://inch-ci.org/) running on this project. 

All this tools are free for open source software like this. I can configure them for you if you give me write access to the repository.

**Comment by verifalia** [comment]
Thanks for the generous offer, @RobertoSchneiders! I have just added you as a collaborator for this project: your help will be greatly appreciated.

**Comment by RobertoSchneiders** [comment]
Thank you @verifalia, I will configure these tools next week.

**Comment by RobertoSchneiders** [comment]
I will reopen this issue until I configure the tools.

**Comment by RobertoSchneiders** [comment]
@verifalia Unfortunately, I can't configure the CI :( . Only the repo admin can. Can you [add the project](https://circleci.com/add-projects) to circle ci? After that I can configure it using a config file.

**Comment by RobertoSchneiders** [comment]
@verifalia Can you also do this for me? http://inch-ci.org/help/webhook

**Comment by RobertoSchneiders** [comment]
@verifalia If you give me admin permissions I can do it

**Comment by verifalia** [comment]
@RobertoSchneiders we have just configured Circle CI and added the webhook for Inch CI. Thank you!
