### ISSUE TITLE
Verifalia support bot is responding all the comments with a programmed e-mail response

### ISSUE THREAD

**Issue by RobertoSchneiders** [verifalia/verifalia-ruby-sdk#8]
This causes a mess in issues and PRs.

@verifalia can you disable it?

**Comment by pramodshinde** [comment]
@RobertoSchneiders  - Agree on this , even its okay to respond programmed emails but this should be only one per discussion/issue. (Should not be repetitive)

**Comment by verifalia** [comment]
Hello,

your recent request has been received and has been assigned a ticket number of [2BE-1DBD2C53-0109].  Please keep this ticket number for your records and include it in the subject (including brackets) of all future emails regarding this issue.  

Our support team will respond to your ticket as soon as possible. In the meanwhile, you may want to visit our knowledge base at:  http://verifalia.com/support/kb  - http://verifalia.com/support/kb 

Thank you.

--
Verifalia support
 http://verifalia.com  - http://verifalia.com   

   

----------------------------------------

**Comment by verifalia** [comment]
Hello,

your recent request has been received and has been assigned a ticket number of [2E7-1DBD2CDB-010B].  Please keep this ticket number for your records and include it in the subject (including brackets) of all future emails regarding this issue.  

Our support team will respond to your ticket as soon as possible. In the meanwhile, you may want to visit our knowledge base at:  http://verifalia.com/support/kb  - http://verifalia.com/support/kb 

Thank you.

--
Verifalia support
 http://verifalia.com  - http://verifalia.com   

   

----------------------------------------
From: verifalia/verifalia-ruby-sdk <reply@reply.github.com>
Sent: Friday, October 23, 2015 7:37 PM
To: verifalia/verifalia-ruby-sdk <verifalia-ruby-sdk@noreply.github.com>
Subject: [verifalia-ruby-sdk] Verifalia support bot is responding all the comments with a programmed e-mail response (#8)

This causes a mess in issues and PRs.  

 @verifalia  - https://github.com/verifalia  can you disable it?

**Comment by verifalia** [comment]
Hello,

your recent request has been received and has been assigned a ticket number of [312-1DBD2EC8-010C].  Please keep this ticket number for your records and include it in the subject (including brackets) of all future emails regarding this issue.  

Our support team will respond to your ticket as soon as possible. In the meanwhile, you may want to visit our knowledge base at:  http://verifalia.com/support/kb  - http://verifalia.com/support/kb 

Thank you.

--
Verifalia support
 http://verifalia.com  - http://verifalia.com   

   

----------------------------------------
From: verifalia/verifalia-ruby-sdk <reply@reply.github.com>
Sent: Friday, October 23, 2015 7:45 PM
To: verifalia/verifalia-ruby-sdk <verifalia-ruby-sdk@noreply.github.com>
Subject: [verifalia-ruby-sdk] Verifalia support bot is responding all the comments with a programmed e-mail response (#8)

This causes a mess in issues and PRs.  

 @verifalia  - https://github.com/verifalia  can you disable it?

**Comment by verifalia** [comment]
Yeah, sorry @RobertoSchneiders and @pramodshinde. Thanks for having reported that, it should be solved now.
